// bd-bridge.ts — One-way bridge: reads bd global memories export → injects as labeled block.
//
// READ-PATH ONLY (Decision 3). This extension:
//   - NEVER writes to bd (constitution: "Pi never writes bd")
//   - NEVER writes to store.jsonl (AC-8: read-path projection only)
//   - ONLY reads ~/.pi/agent/bridge/global-export.jsonl at before_agent_start
//
// The export file is generated by bridge/export-bd-global.sh (run manually or via alias).
// Bridged facts appear as [FROM bridge, exported <timestamp>] — visibly labeled,
// never merged into pi's own memory.
//
// Filters: only constraint/exact/preference/reason/decision categories (skip
// sisyphus-internal: session-*, pre-test:*, next-session:*, files:*).

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { readFileSync, existsSync, statSync, appendFileSync } from "node:fs";
import { scanSecrets } from "../memory/scanner.ts";
import { join } from "node:path";
import * as os from "node:os";

const BRIDGE_FILE = join(os.homedir(), ".pi", "agent", "bridge", "global-export.jsonl");

const BRIDGED_CATEGORIES = ["constraint", "exact", "preference", "reason", "decision"];

const CATEGORY_PRIORITY: Record<string, number> = {
    constraint: 0,
    decision: 1,
    reason: 2,
    exact: 3,
    preference: 4,
};

/**
 * Parse a raw export entry into a clean bridged entry.
 * Handles two write-path schemas:
 * - Schema A (direct `bd remember`): value = "category:content" (clean, prefixed)
 * - Schema B (bd_remember.py wrapper): value = "scope=X|turn=Y|category=Z|key=K|value=V"
 * Returns null if the entry is not in a bridged category.
 * Known limitation: does not handle escaped pipes (\|) in schema B values.
 */
function parseBridgeEntry(raw: BridgeEntry): BridgeEntry | null {
    const { export_timestamp, key, value } = raw;

    // Legacy schema A — frozen, remove when export contains 0 schema-A lines
    for (const cat of BRIDGED_CATEGORIES) {
        if (value.startsWith(`${cat}:`)) {
            return { export_timestamp, key, value };
        }
    }

    // Schema B: pipe-delimited bd record — value field is last; head fields are slug-safe
    if (value.startsWith("scope=")) {
        const vi = value.indexOf("|value=");
        if (vi === -1) return null;
        const head = value.substring(0, vi);
        const cleanValue = value.substring(vi + 7).replace(/\\\|/g, "|");
        let category = "";
        for (const part of head.split("|")) {
            const eq = part.indexOf("=");
            if (eq !== -1 && part.substring(0, eq) === "category") {
                category = part.substring(eq + 1);
            }
        }
        if (BRIDGED_CATEGORIES.includes(category) && cleanValue) {
            return { export_timestamp, key, value: `${category}:${cleanValue}` };
        }
    }

    return null;
}

const MAX_CHARS = 6000;

interface BridgeEntry {
    export_timestamp: string;
    key: string;
    value: string;
}

function readBridgeExport(): { entries: BridgeEntry[]; exportTimestamp: string | null; telemetry: { read: number; parsed: number; dropped: number; secret: number } } {
    if (!existsSync(BRIDGE_FILE)) return { entries: [], exportTimestamp: null, telemetry: { read: 0, parsed: 0, dropped: 0, secret: 0 } };

    const content = readFileSync(BRIDGE_FILE, "utf-8");
    const entries: BridgeEntry[] = [];
    let exportTimestamp: string | null = null;
    let read = 0, parsed = 0, dropped = 0, secret = 0;

    for (const line of content.split("\n")) {
        if (!line.trim()) continue;
        read++;
        try {
            const raw = JSON.parse(line) as BridgeEntry;
            if (!exportTimestamp) exportTimestamp = raw.export_timestamp;
            const result = parseBridgeEntry(raw);
            if (result) {
                // W3: secret-scan bridged values at inject. The bridge bypasses memory_remember's
                // write-boundary scan, so scan here and refuse + log on a hit (never inject a likely
                // secret into the system prompt). Curated export keeps practical risk low; defense-in-depth.
                const scan = scanSecrets(result.value);
                if (scan.detected) { secret++; dropped++; }
                else { parsed++; entries.push(result); }
            }
            else dropped++;
        } catch { dropped++; }
    }
    return { entries, exportTimestamp, telemetry: { read, parsed, dropped, secret } };
}

function checkStale(_exportTimestamp: string): string | null {
    const candidates = [
        join(os.homedir(), "Main-vault", ".beads", "embeddeddolt"),
        join(os.homedir(), ".beads", "beads_global.db"),
        join(os.homedir(), ".local", "share", "beads", "beads_global.db"),
    ];
    for (const dbPath of candidates) {
        if (!existsSync(dbPath)) continue;
        try {
            const dbMtime = statSync(dbPath).mtimeMs;
            const exportTime = new Date(_exportTimestamp).getTime();
            if (dbMtime > exportTime + 60000) return "stale";
        } catch { /* ignore */ }
    }
    return null;
}

export default function (pi: ExtensionAPI) {
    pi.on("before_agent_start", async (event) => {
        const { entries, exportTimestamp, telemetry } = readBridgeExport();
        if (entries.length === 0 || !exportTimestamp) return;

        entries.sort((a, b) => {
            const catA = a.value.split(":")[0];
            const catB = b.value.split(":")[0];
            return (CATEGORY_PRIORITY[catA] ?? 99) - (CATEGORY_PRIORITY[catB] ?? 99);
        });

        const lines = entries.map(e => `- ${e.value}`);
        let block = lines.join("\n");
        let injected = entries.length;
        let omittedBudget = 0;

        if (block.length > MAX_CHARS) {
            let fitLen = 0;
            let fitCount = 0;
            for (const line of lines) {
                const candidate = fitLen === 0 ? line.length : fitLen + 1 + line.length;
                if (candidate > MAX_CHARS) break;
                fitLen = candidate;
                fitCount++;
            }
            injected = fitCount;
            omittedBudget = entries.length - fitCount;
            block = lines.slice(0, fitCount).join("\n") + `\n…+${omittedBudget} bridge entries omitted`;
        }

        const stale = checkStale(exportTimestamp);
        const header = stale
            ? `[FROM bridge, exported ${exportTimestamp} — ⚠️ STALE: bd modified after export]`
            : `[FROM bridge, exported ${exportTimestamp}]`;

        const TELEMETRY_FILE = join(os.homedir(), ".pi", "agent", "bridge", "telemetry.log");
        try {
            appendFileSync(TELEMETRY_FILE,
                `${new Date().toISOString()} read=${telemetry.read} parsed=${telemetry.parsed} dropped=${telemetry.dropped} secret=${telemetry.secret} injected=${injected} omitted_budget=${omittedBudget}\n`);
        } catch { /* non-critical */ }

        return { systemPrompt: event.systemPrompt + "\n\n" + header + "\n" + block };
    });
}
